# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cluster_pb2 as cluster__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cluster_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerServiceStub(object):
    """Worker-side service, called by master.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/cluster.WorkerService/GetStatus',
                request_serializer=cluster__pb2.WorkerId.SerializeToString,
                response_deserializer=cluster__pb2.WorkerDescriptor.FromString,
                _registered_method=True)
        self.InitShard = channel.unary_unary(
                '/cluster.WorkerService/InitShard',
                request_serializer=cluster__pb2.InitShardRequest.SerializeToString,
                response_deserializer=cluster__pb2.InitShardResponse.FromString,
                _registered_method=True)
        self.RunStage = channel.stream_stream(
                '/cluster.WorkerService/RunStage',
                request_serializer=cluster__pb2.StageRequest.SerializeToString,
                response_deserializer=cluster__pb2.StageResponse.FromString,
                _registered_method=True)
        self.HealthStream = channel.stream_stream(
                '/cluster.WorkerService/HealthStream',
                request_serializer=cluster__pb2.HealthPing.SerializeToString,
                response_deserializer=cluster__pb2.HealthPong.FromString,
                _registered_method=True)


class WorkerServiceServicer(object):
    """Worker-side service, called by master.

    """

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunStage(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=cluster__pb2.WorkerId.FromString,
                    response_serializer=cluster__pb2.WorkerDescriptor.SerializeToString,
            ),
            'InitShard': grpc.unary_unary_rpc_method_handler(
                    servicer.InitShard,
                    request_deserializer=cluster__pb2.InitShardRequest.FromString,
                    response_serializer=cluster__pb2.InitShardResponse.SerializeToString,
            ),
            'RunStage': grpc.stream_stream_rpc_method_handler(
                    servicer.RunStage,
                    request_deserializer=cluster__pb2.StageRequest.FromString,
                    response_serializer=cluster__pb2.StageResponse.SerializeToString,
            ),
            'HealthStream': grpc.stream_stream_rpc_method_handler(
                    servicer.HealthStream,
                    request_deserializer=cluster__pb2.HealthPing.FromString,
                    response_serializer=cluster__pb2.HealthPong.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cluster.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cluster.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """Worker-side service, called by master.

    """

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cluster.WorkerService/GetStatus',
            cluster__pb2.WorkerId.SerializeToString,
            cluster__pb2.WorkerDescriptor.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cluster.WorkerService/InitShard',
            cluster__pb2.InitShardRequest.SerializeToString,
            cluster__pb2.InitShardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunStage(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/cluster.WorkerService/RunStage',
            cluster__pb2.StageRequest.SerializeToString,
            cluster__pb2.StageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/cluster.WorkerService/HealthStream',
            cluster__pb2.HealthPing.SerializeToString,
            cluster__pb2.HealthPong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MasterAdminServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListWorkers = channel.unary_unary(
                '/cluster.MasterAdminService/ListWorkers',
                request_serializer=cluster__pb2.Empty.SerializeToString,
                response_deserializer=cluster__pb2.WorkerList.FromString,
                _registered_method=True)


class MasterAdminServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListWorkers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterAdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListWorkers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkers,
                    request_deserializer=cluster__pb2.Empty.FromString,
                    response_serializer=cluster__pb2.WorkerList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cluster.MasterAdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cluster.MasterAdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MasterAdminService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListWorkers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cluster.MasterAdminService/ListWorkers',
            cluster__pb2.Empty.SerializeToString,
            cluster__pb2.WorkerList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
